"""Entity property display/categorization + TTL-display helpers (split from helpers.py)."""
import rdflib
from sqlalchemy import select

from web.models import db, OntologyEntity, OntologyVersion

from .shapes import _class_target_shapes_graph


# Local-name keys of the crosswalk predicates above, for suppressing duplicate
# rendering: an IRI-valued source/seeAlso/match triple is surfaced by the
# Mappings & provenance card and must not ALSO render as a Properties
# relationship row (the same DOI link showed twice on principle-class pages).
_CROSSWALK_KEYS = frozenset({'source', 'seealso', 'references', 'exactmatch',
                             'closematch', 'broadmatch', 'relatedmatch'})


# Property keys that represent extraction/provenance metadata (sidebar)
_EXTRACTION_META_KEYS = frozenset({
    'discoveredincase', 'discoveredinpass', 'discoveredinsection',
    'firstdiscoveredat', 'firstdiscoveredincase',
    'generatedattime', 'generatedAtTime',
    'wasattributedto', 'wasGeneratedBy',
    # Commit-time match provenance (proeth-prov). Without these entries the
    # keys fall through to groups['core'] and render as if they were bearer
    # attributes (nine-component correspondence audit, 2026-07-05).
    'matchconfidence', 'matchreasoning', 'matchedontologylabel',
    'matchedontologyclass', 'matchesexisting', 'synthesisliteral',
})

_EVIDENCE_KEYS = frozenset({'sourcetext', 'textreferences'})

_DESCRIPTION_KEYS = frozenset({'caseinvolvement', 'casecontext'})

# Property keys to skip entirely (redundant or internal).
# dtupleComponent: the D-tuple letter (R/P/O/...) is already shown in the page header.
# changeNote is version history: internal change rationale, kept in the TTL and the
# DB version rows but not rendered on the public pages (2026-07-06 decision; the
# iao:0000116 editor note, by contrast, is deliberate display and prompt content).
_SKIP_KEYS = frozenset({'type', 'NamedIndividual', 'rdf_types', 'rdf_superclasses', 'dtupleComponent', 'changeNote'})

# Definition-layer keys -> the Definition card (kept out of the raw "core" property list).
_DEFINITION_LAYER_GROUP = {
    'definition': 'definition',          # skos:definition textual definition (primary)
    'IAO_0000115': 'definition',         # IAO textual definition (primary; same group)
    'IAO_0000119': 'definition_source',  # definition source / citations
    'IAO_0000116': 'editor_note',        # editor note / extraction framing
}

# Human-readable labels for property keys
_PROPERTY_LABELS = {
    'roleclass': 'Role Class',
    'rolecategory': 'Role Category',
    'importance': 'Importance',
    'confidence': 'Confidence',
    'attributes': 'Attributes',
    'relationships': 'Relationships',
    'caseinvolvement': 'Case Involvement',
    'sourcetext': 'Source Text',
    'textreferences': 'Text References',
    'discoveredincase': 'Discovered in Case',
    'discoveredinpass': 'Discovered in Pass',
    'discoveredinsection': 'Discovered in Section',
    'firstdiscoveredat': 'First Discovered',
    'firstdiscoveredincase': 'First Case',
    'generatedattime': 'Generated',
    'generatedAtTime': 'Generated',
    'wasattributedto': 'Attributed To',
    'wasGeneratedBy': 'Generated By',
    'discoveredInCase': 'Discovered in Case',
}


def _humanize_property_key(key):
    """Convert a property key to a human-readable label (shared with the cards)."""
    from web.property_labels import humanize_key
    return humanize_key(key)


def _format_property_value(value):
    """Format a property value for display, handling dict-like strings."""
    if not isinstance(value, str):
        return value
    s = value.strip()
    # Detect Python dict-like strings: {'key': 'value'}
    if s.startswith('{') and s.endswith('}') and "'" in s:
        try:
            import ast
            parsed = ast.literal_eval(s)
            if isinstance(parsed, dict):
                return parsed
        except (ValueError, SyntaxError):
            pass
    return value


def categorize_entity_properties(entity):
    """Categorize entity properties into display groups.

    Returns a dict with keys:
        description: list of (label, value) for case involvement text
        core: list of (label, value) for literal-valued entity attributes
        relationships: list of (predicate_key, [iri, ...]) for IRI-valued
            object-property triples (rendered like the case-page cards)
        evidence: list of (label, value) for source text references
        extraction_meta: list of (label, value) for provenance metadata
    """
    groups = {
        'description': [],
        'definition': [],
        'gloss': [],
        'definition_source': [],
        'editor_note': [],
        'scope_notes': [],
        'core': [],
        'relationships': [],
        'evidence': [],
        'extraction_meta': [],
    }

    if not entity.properties:
        return groups

    for key, value in entity.properties.items():
        # Skip internal keys, the rdf_types list (the materialized direct type is
        # shown as the concept chip in the header instead), the <concept>class
        # key (shown as the "instance of" link instead), and the retired
        # conceptCategory literal (VIEW-1 / VER-1: no longer written, but legacy
        # committed entities still carry it; the concept chip conveys the category).
        if (key in _SKIP_KEYS or key.lower() == 'rdf_types'
                or key.lower() == 'conceptcategory' or key.lower().endswith('class')):
            continue

        # Skip a literal identical to the entity's rdfs:comment: the commit
        # routes one descriptor field (caseInvolvement, concreteExpression,
        # obligationStatement, ...) into the comment AND keeps the field
        # literal, and the Definition card already shows the comment.
        if isinstance(value, str) and value == (getattr(entity, 'comment', None) or ''):
            continue

        # The displaced rdfs:comment gloss: the sync extractor stores it under
        # 'comment' only when iao:0000115 won the comment column (S-DISP-2), so
        # this is exactly the class-level gloss the definition_card renders as
        # the muted secondary line.
        if key.lower() == 'comment':
            vals = value if isinstance(value, list) else [value]
            groups['gloss'].extend(str(v) for v in vals if v)
            continue

        # skos:scopeNote is an inherited / contextual definition (e.g. the matched
        # parent class's definition), distinct from the entity's own primary
        # definition (rdfs:comment / skos:definition). Collect the raw values so the
        # Definition card can render them demarcated rather than burying them as a
        # core attribute. Each value carries a leading [source] tag from commit time.
        if key.lower() == 'scopenote':
            vals = value if isinstance(value, list) else [value]
            groups['scope_notes'].extend(str(v) for v in vals if v)
            continue

        # IAO definition layer -> the Definition card, not the raw core list:
        # IAO_0000115 (definition text), IAO_0000119 (definition source), IAO_0000116 (editor note).
        if key in _DEFINITION_LAYER_GROUP:
            vals = value if isinstance(value, list) else [value]
            groups[_DEFINITION_LAYER_GROUP[key]].extend(str(v) for v in vals if v)
            continue

        # IRI-valued triples are object properties (R->P->O / defeasibility
        # edges); group them as relationships, keeping the bare predicate and the
        # target IRIs so the template can link them (mirrors the card view).
        # Crosswalk predicates are excluded: the Mappings & provenance card owns
        # them (entity_semantic_links), and the literal-valued proeth:source
        # provision string on Constraint individuals is unaffected because it
        # takes the attribute branch below.
        iris = iri_values(value)
        if iris is not None:
            if key.lower() in _CROSSWALK_KEYS:
                continue
            groups['relationships'].append((key, iris))
            continue

        label = _humanize_property_key(key)
        formatted = _format_property_value(value) if isinstance(value, str) else value
        # Format list items too
        if isinstance(value, list):
            formatted = [_format_property_value(v) for v in value]

        entry = (label, formatted)

        if key.lower() in {k.lower() for k in _DESCRIPTION_KEYS}:
            groups['description'].append(entry)
        elif key.lower() in {k.lower() for k in _EVIDENCE_KEYS}:
            groups['evidence'].append(entry)
        elif key.lower() in {k.lower() for k in _EXTRACTION_META_KEYS}:
            groups['extraction_meta'].append(entry)
        else:
            groups['core'].append(entry)

    return groups


def iri_values(value):
    """Return a list of IRI strings if value is IRI-valued (object property),
    else None. Mirrors the literal-vs-IRI split used by the case-page cards."""
    if isinstance(value, str) and value.startswith(('http://', 'https://')):
        return [value]
    if isinstance(value, (list, tuple)) and value and isinstance(value[0], str) \
            and value[0].startswith(('http://', 'https://')):
        return [v for v in value if isinstance(v, str) and v.startswith(('http://', 'https://'))]
    return None


def generate_entity_ttl_display(entity, ontology):
    """TTL for display. Render the entity's ACTUAL source triples from the ontology's
    current version. This way skos:exactMatch, skos:inScheme, skos:Concept typing,
    skos:definition, and dcterms:source all show, not just the few fields the entity
    extractor stored, PLUS the descriptive SHACL shapes targeting the class (so the TTL is
    self-contained: the class and its definitional field schema). Fall back to the reconstruction
    if the source cannot be read."""
    try:
        v = db.session.execute(
            select(OntologyVersion).where(
                OntologyVersion.ontology_id == ontology.id,
                OntologyVersion.is_current.is_(True)
            )
        ).scalar_one_or_none()
        if v and v.content:
            g = rdflib.Graph()
            g.parse(data=v.content, format='turtle')
            subj = rdflib.URIRef(entity.uri)
            sub = rdflib.Graph()
            for prefix, ns in g.namespaces():
                sub.bind(prefix, ns)
            for p, o in g.predicate_objects(subj):
                sub.add((subj, p, o))
                # Pull one level of blank-node closure so owl:Restriction nodes render.
                if isinstance(o, rdflib.BNode):
                    for p2, o2 in g.predicate_objects(o):
                        sub.add((o, p2, o2))
            # Append the descriptive SHACL shapes targeting this class (self-contained TTL): SHACL is
            # a separate graph (not entailed), so the field schema would otherwise be absent.
            shapes_g = _class_target_shapes_graph(entity)
            if len(shapes_g):
                for prefix, ns in shapes_g.namespaces():
                    sub.bind(prefix, ns)
                for t in shapes_g:
                    sub.add(t)
            if len(sub):
                return sub.serialize(format='turtle')
    except Exception:
        pass
    from web.rdf_helpers import generate_entity_ttl
    return generate_entity_ttl(entity, ontology)


def extract_entity_from_ttl(ttl_content, ontology, fragment):
    """Extract a single entity's data from TTL content for versioned display.

    Returns a dict-like object with entity attributes, or None if not found.
    """
    g = rdflib.Graph()
    try:
        g.parse(data=ttl_content, format='turtle')
    except Exception:
        return None

    # Find the entity URI by fragment
    target_uri = None
    for s in g.subjects():
        s_str = str(s)
        if s_str.endswith(f'#{fragment}'):
            target_uri = s
            break

    if not target_uri:
        return None

    from rdflib import RDF, RDFS, OWL

    # Determine type
    entity_type = 'class'
    for type_uri in g.objects(target_uri, RDF.type):
        if type_uri == OWL.ObjectProperty or type_uri == OWL.DatatypeProperty:
            entity_type = 'property'
        elif type_uri == OWL.NamedIndividual:
            entity_type = 'individual'

    label = next(g.objects(target_uri, RDFS.label), None)
    comment = next(g.objects(target_uri, RDFS.comment), None)
    parent = next(g.objects(target_uri, RDFS.subClassOf), None)
    domain = next(g.objects(target_uri, RDFS.domain), None)
    range_val = next(g.objects(target_uri, RDFS.range), None)

    uri_str = str(target_uri)
    label_str = str(label) if label else None
    comment_str = str(comment) if comment else None
    content_hash = OntologyEntity.compute_content_hash(uri_str, label_str, comment_str)

    # Build TTL snippet for display
    from web.rdf_helpers import generate_entity_ttl

    class _EntityProxy:
        """Lightweight proxy mimicking OntologyEntity for TTL generation."""
        pass

    proxy = _EntityProxy()
    proxy.uri = uri_str
    proxy.label = label_str
    proxy.comment = comment_str
    proxy.entity_type = entity_type
    proxy.parent_uri = str(parent) if parent else None
    proxy.domain = str(domain) if domain else None
    proxy.range = str(range_val) if range_val else None
    proxy.properties = None
    proxy.content_hash = content_hash
    proxy.updated_at = None
    proxy.id = None
    proxy._ttl = generate_entity_ttl(proxy, ontology)

    return proxy
