"""
Deterministic Wolfram Cloud backend for the ontology-supported language pipeline.

SKETCH. This is the structural skeleton specified in
`docs-internal/wolfram_linguistic_pipeline_design.md` (Section 4.2). It provides
the deterministic linguistic primitives that the AgentOne chat path
(`wolfram_service.py`) cannot: word-sense enumeration, lexical-relation
(hypernym) chains, and shallow predicate-argument structure. Results are typed,
not prose.

Separation of concerns:
    - wolfram_service.WolframService  -> AgentOne chat completions (prose).
    - wolfram_cloud_backend (this)    -> named Wolfram Language functions
                                         evaluated in the Wolfram Cloud,
                                         returning structured values.
The two paths fail independently and use independent credentials.

Authentication (open decision, see design doc Section 9):
    The Wolfram Client Library authenticates a cloud session with a Secured
    Authentication Key, a (consumer_key, consumer_secret) pair generated by
    GenerateSecuredAuthenticationKey[] in the Wolfram Language. That is the
    primary path implemented below. If the issued developer credential is
    instead a single bearer key tied to a deployed APIFunction, use the
    `_evaluate_via_api` transport stub instead of the session transport; the
    linguistic methods do not change.

Reference:
    https://reference.wolfram.com/language/workflow/ConnectPythonToTheWolframCloud.html
    https://wolframresearch.github.io/WolframClientForPython/

Per workspace policy: no silent fallbacks. A missing library, missing
credential, or failed evaluation surfaces as an explicit error (raised at
construction for configuration faults; returned in a structured Result for
per-call faults).
"""

from __future__ import annotations

import logging
import os
import time
from dataclasses import dataclass, field
from typing import Any, Generic, List, Optional, TypeVar

logger = logging.getLogger(__name__)

T = TypeVar("T")


# ---------------------------------------------------------------------------
# Result wrapper and data contracts (design doc Section 6)
# ---------------------------------------------------------------------------


@dataclass
class Result(Generic[T]):
    """Per-call outcome. Structured failure rather than an exception across
    the boundary, matching the WolframService convention."""

    success: bool
    data: Optional[T] = None
    error: Optional[str] = None
    elapsed_ms: int = 0


@dataclass
class LexicalSense:
    """One sense of a term, from WordData. The `sense_id` is the stable
    WordNet-style key persisted by the Sense Registry."""

    term: str
    sense_id: str          # e.g. "report::noun::1" (document-submission sense)
    part_of_speech: str
    gloss: str
    rank: int = 0          # 0 = top-ranked candidate
    source: str = "WordData"


@dataclass
class HypernymChain:
    """Ordered superordinate terms for a chosen sense. Evidence for
    rdfs:subClassOf placement, never an authoritative assertion."""

    term: str
    sense_id: str
    parents: List[str] = field(default_factory=list)   # nearest first
    confidence: float = 0.0
    source: str = "WordData"


@dataclass
class FrameArgument:
    role: str              # grammatical/semantic role label
    span: str              # surface text of the argument


@dataclass
class ShallowFrameParse:
    """Predicate-argument approximation from TextStructure. The principled
    LTAG-frame parse reduces to this same shape (design doc Section 4.4)."""

    sentence: str
    predicate: str
    arguments: List[FrameArgument] = field(default_factory=list)
    negated: bool = False
    modality: Optional[str] = None     # e.g. "deontic" when a modal is present
    source: str = "TextStructure"


# ---------------------------------------------------------------------------
# Backend
# ---------------------------------------------------------------------------


class WolframCloudBackendError(RuntimeError):
    """Raised for configuration faults (missing library or credential)."""


class WolframCloudBackend:
    """
    Deterministic linguistic primitives evaluated in the Wolfram Cloud.

    Credentials are read from the environment, kept distinct from the AgentOne
    key so the two Wolfram paths fail independently:
        WOLFRAM_CLOUD_CONSUMER_KEY      consumer key of the Secured Auth Key
        WOLFRAM_CLOUD_CONSUMER_SECRET   consumer secret of the Secured Auth Key
    (Alternative single-key/APIFunction transport: WOLFRAM_CLOUD_API_KEY.)
    """

    def __init__(
        self,
        consumer_key: Optional[str] = None,
        consumer_secret: Optional[str] = None,
        timeout: int = 60,
    ):
        self.consumer_key = consumer_key or os.environ.get("WOLFRAM_CLOUD_CONSUMER_KEY", "")
        self.consumer_secret = consumer_secret or os.environ.get("WOLFRAM_CLOUD_CONSUMER_SECRET", "")
        self.timeout = timeout
        self._session = None  # lazily started WolframCloudSession

    # -- configuration ------------------------------------------------------

    @property
    def is_configured(self) -> bool:
        return bool(self.consumer_key and self.consumer_secret)

    def get_status(self) -> dict:
        return {
            "service": "Wolfram Cloud (deterministic backend)",
            "configured": self.is_configured,
            "timeout_seconds": self.timeout,
            "session_active": self._session is not None,
        }

    # -- session management -------------------------------------------------

    def _ensure_session(self):
        """Lazily create and start an authenticated cloud session. Raises a
        clear configuration error rather than degrading silently."""
        if self._session is not None:
            return self._session

        if not self.is_configured:
            raise WolframCloudBackendError(
                "Wolfram Cloud credentials missing: set WOLFRAM_CLOUD_CONSUMER_KEY "
                "and WOLFRAM_CLOUD_CONSUMER_SECRET."
            )

        try:
            from wolframclient.evaluation import (  # local import keeps the
                SecuredAuthenticationKey,           # module importable without
                WolframCloudSession,                # the optional dependency
            )
        except ImportError as exc:
            raise WolframCloudBackendError(
                "wolframclient is not installed. Add it to the OntServe venv: "
                "pip install wolframclient"
            ) from exc

        sak = SecuredAuthenticationKey(self.consumer_key, self.consumer_secret)
        session = WolframCloudSession(credentials=sak)
        session.start()
        if not session.authorized():
            raise WolframCloudBackendError("Wolfram Cloud session failed to authorize.")
        self._session = session
        return session

    def close(self):
        if self._session is not None:
            self._session.terminate()
            self._session = None

    def _evaluate(self, expr) -> Result[Any]:
        """Evaluate a Wolfram Language expression in the cloud and return the
        decoded Python value. `expr` is built with wolframclient.language.wl
        or wlexpr by the caller."""
        start = time.monotonic()
        try:
            session = self._ensure_session()
            value = session.evaluate(expr)
            elapsed = int((time.monotonic() - start) * 1000)
            logger.info("Wolfram Cloud evaluate ok in %dms", elapsed)
            return Result(success=True, data=value, elapsed_ms=elapsed)
        except WolframCloudBackendError:
            raise  # configuration faults propagate; not a per-call failure
        except Exception as exc:  # noqa: BLE001 - boundary: report, do not crash callers
            elapsed = int((time.monotonic() - start) * 1000)
            logger.error("Wolfram Cloud evaluate failed: %s", exc, exc_info=True)
            return Result(success=False, error=str(exc), elapsed_ms=elapsed)

    # -- alternative transport (single bearer key / deployed APIFunction) ---

    def _evaluate_via_api(self, api_path: str, params: dict) -> Result[Any]:
        """Stub for the single-key transport. Use only if the issued credential
        is a bearer key for a deployed APIFunction rather than a Secured
        Authentication Key. Implement with WolframAPICall / requests against the
        deployed endpoint. Left unimplemented pending credential confirmation."""
        raise NotImplementedError(
            "Single-key APIFunction transport not implemented. Confirm credential "
            "type (see module docstring) before choosing this path."
        )

    # -- linguistic primitives (pipeline stages 2-4) -----------------------

    def disambiguate(self, term: str, context: str = "") -> Result[List[LexicalSense]]:
        """
        Stage 2. Enumerate candidate senses for a term.

        WordData enumerates WordNet senses; it does not itself rank by context.
        This method returns the enumerated senses, and `context` is reserved for
        a ranking step (an embedding similarity or an AgentOne tiebreak) that the
        caller applies before grounding. Honest about the boundary: the builtin
        gives the candidate set, not the contextual choice.

        WL: WordData[term, "Senses"] and per-sense WordData[{term, sense},
            "Definitions"] / "PartsOfSpeech".
        """
        from wolframclient.language import wl  # noqa: F401 - used when implemented

        # expr = wl.WordData(term, "Senses")
        # raw = self._evaluate(expr)
        # ... decode raw senses into List[LexicalSense], assign sense_id and rank,
        #     optionally re-rank by `context` ...
        raise NotImplementedError("disambiguate: build WordData senses expr and parse")

    def lexical_parents(self, term: str, sense_id: str) -> Result[HypernymChain]:
        """
        Stage 3. Hypernym chain for a chosen sense, as candidate superclass
        evidence for the grounding adapter.

        WL: WordData[{term, sense}, "Hypernyms", "Words"], walked to the root to
            build the ordered `parents` list.
        """
        from wolframclient.language import wl  # noqa: F401

        # expr = wl.WordData([term, _sense_token(sense_id)], "Hypernyms", "Words")
        # raw = self._evaluate(expr)
        # ... decode into HypernymChain, set confidence from chain depth / sense rank ...
        raise NotImplementedError("lexical_parents: build WordData hypernyms expr and parse")

    def parse_structure(self, sentence: str) -> Result[ShallowFrameParse]:
        """
        Stage 4 (shallow). Predicate-argument approximation.

        There is no single SRL builtin; TextStructure yields a dependency or
        constituent parse from which the main predicate and its dependents are
        extracted as a coarse frame. Negation and modality are read off the parse
        (a modal auxiliary flags `modality="deontic"` for downstream obligation
        mapping). The principled parse comes from the LTAG-frame parser the
        research stay integrates; it reduces to this same ShallowFrameParse shape.

        WL: TextStructure[sentence, "ConstituentGraphs"] or the dependency parse.
        """
        from wolframclient.language import wl  # noqa: F401

        # expr = wl.TextStructure(sentence, "ConstituentGraphs")
        # raw = self._evaluate(expr)
        # ... extract predicate + FrameArgument list, detect negation/modality ...
        raise NotImplementedError("parse_structure: build TextStructure expr and parse")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _sense_token(sense_id: str) -> Any:
    """Translate a Sense Registry sense_id back into the WordData sense token
    (e.g. {"report", "Noun", 1}). Implement alongside the registry schema."""
    raise NotImplementedError
