#!/usr/bin/env python3
"""
Export the ProEthica ontology corpus for an archival (Zenodo / tagged-release)
deposit referenced in the KI2026 #94 camera-ready.

Dumps the current (is_current) version of every proethica-case-N case ontology
plus the core / intermediate / domain / provenance ontologies and the three
NSPE-tradition professional codes from the OntServe `ontology_versions` table to
individual .ttl files, then writes MANIFEST.md (per-file triple counts, content
hashes, and the namespaces in use).

The per-case TTLs do not exist as files on disk; they live only in the database.
This script is the canonical export path for the deposit.

Read-only against the database. Writes only to the output directory.

    python validation/export_corpus_deposit.py [--out DIR]
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

import rdflib

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "web"))

from config.config_loader import load_ontserve_config  # noqa: E402

load_ontserve_config()

from flask import Flask  # noqa: E402
from web.app_config import config as flask_config  # noqa: E402
from web.models import db, init_db, Ontology, OntologyVersion  # noqa: E402

# Non-case ontologies to include, by DB `name`. Grouped for the manifest.
SUPPORT_ONTOLOGIES = {
    "core": ["proethica-core"],
    "intermediate": ["proethica-intermediate"],
    "domain": ["engineering-ethics", "proethica-cases"],
    "provenance": ["proethica-provenance"],
    "professional-codes": [
        "ASCE Code of Ethics",
        "ASME Code of Ethics",
        "IEEE Code of Ethics",
    ],
}


def make_app() -> Flask:
    app = Flask(__name__)
    app.config.from_object(flask_config[os.environ.get("FLASK_CONFIG", "development")])
    init_db(app)
    return app


def current_content(name: str):
    ont = Ontology.query.filter_by(name=name).first()
    if ont is None:
        return None, None
    ver = OntologyVersion.query.filter_by(ontology_id=ont.id, is_current=True).first()
    if ver is None:
        return ont, None
    return ont, ver


def slugify(name: str) -> str:
    return name.lower().replace(" ", "_")


def analyze(content: str):
    """Return (triple_count, sorted prefix->namespace map) for a TTL string."""
    g = rdflib.Graph()
    g.parse(data=content, format="turtle")
    ns = {p: str(n) for p, n in g.namespaces()}
    return len(g), ns


def write_file(path: Path, content: str) -> dict:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    n_triples, ns = analyze(content)
    return {
        "file": str(path.relative_to(path.parents[1])),
        "triples": n_triples,
        "bytes": len(content.encode()),
        "sha256": hashlib.sha256(content.encode()).hexdigest(),
        "namespaces": ns,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(ROOT / "deposit" / "ki2026"),
                    help="Output directory (default: OntServe/deposit/ki2026).")
    args = ap.parse_args()
    out = Path(args.out)

    app = make_app()
    records = {"cases": [], "support": {}}
    all_ns: dict = {}
    missing = []

    with app.app_context():
        # Case ontologies
        cases = (
            Ontology.query
            .filter(Ontology.name.op("~")("^proethica-case-[0-9]+$"))
            .order_by(Ontology.name)
            .all()
        )
        case_dir = out / "case-ontologies"
        for ont in cases:
            ver = OntologyVersion.query.filter_by(
                ontology_id=ont.id, is_current=True
            ).first()
            if ver is None:
                missing.append(ont.name)
                continue
            rec = write_file(case_dir / f"{ont.name}.ttl", ver.content)
            all_ns.update(rec.pop("namespaces"))
            records["cases"].append(rec)

        # Support ontologies, grouped
        ont_dir = out / "ontologies"
        for group, names in SUPPORT_ONTOLOGIES.items():
            records["support"][group] = []
            for name in names:
                ont, ver = current_content(name)
                if ver is None:
                    missing.append(name)
                    continue
                rec = write_file(ont_dir / f"{slugify(name)}.ttl", ver.content)
                all_ns.update(rec.pop("namespaces"))
                records["support"][group].append(rec)

    # Manifest
    n_cases = len(records["cases"])
    case_triples = sum(r["triples"] for r in records["cases"])
    lines = [
        "# ProEthica Ontology Corpus -- Archival Deposit Manifest",
        "",
        "Generated by `OntServe/validation/export_corpus_deposit.py` "
        "for the KI2026 #94 camera-ready reproducibility release.",
        "",
        "## Contents",
        "",
        f"- **Case ontologies**: {n_cases} files "
        f"(`case-ontologies/proethica-case-N.ttl`), {case_triples} triples total.",
    ]
    for group, recs in records["support"].items():
        names = ", ".join(Path(r["file"]).name for r in recs)
        lines.append(f"- **{group}**: {len(recs)} file(s) -- {names}")
    if missing:
        lines += ["", "## Missing (no current version found)", ""]
        lines += [f"- {m}" for m in missing]

    lines += ["", "## Namespaces", ""]
    for p in sorted(all_ns):
        lines.append(f"- `{p or '(default)'}`: {all_ns[p]}")

    lines += ["", "## File inventory (triples / sha256)", ""]
    lines.append("| File | Triples | SHA-256 |")
    lines.append("|------|--------:|---------|")
    for r in records["cases"]:
        lines.append(f"| {r['file']} | {r['triples']} | `{r['sha256'][:16]}...` |")
    for group, recs in records["support"].items():
        for r in recs:
            lines.append(f"| {r['file']} | {r['triples']} | `{r['sha256'][:16]}...` |")

    out.mkdir(parents=True, exist_ok=True)
    (out / "MANIFEST.md").write_text("\n".join(lines) + "\n")

    print(f"Exported {n_cases} case ontologies + "
          f"{sum(len(v) for v in records['support'].values())} support ontologies to {out}")
    print(f"Total case triples: {case_triples}")
    if missing:
        print("MISSING current versions:", missing)
    print(f"Manifest: {out / 'MANIFEST.md'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
