"""Shared human-readable labels for entity property keys.

Single source of truth for both the case-page cards and the entity detail page,
so the two views label the same property identically. ProEthica emits many keys
as lower-case concatenations (e.g. ``rolecategory``, ``caseinvolvement``) that a
generic camelCase splitter cannot break apart, so they are mapped explicitly.
"""

import re

# Curated labels for the property keys that surface in the case views. Keys are
# matched case-insensitively (see humanize_key).
PROPERTY_LABELS = {
    # Concept-specific descriptive fields
    'caseinvolvement': 'Case involvement',
    'casecontext': 'Case context',
    'rolecategory': 'Role category',
    'rolelabel': 'Role',
    'proficiencylevel': 'Proficiency level',
    'capabilitystatement': 'Capability statement',
    'constraintstatement': 'Constraint statement',
    'obligationstatement': 'Obligation statement',
    'compliancestatus': 'Compliance status',
    'concreteexpression': 'Concrete expression',
    'interpretation': 'Interpretation',
    'balancingwith': 'Balancing with',
    'tensionresolution': 'Tension resolution',
    'demonstratedthrough': 'Demonstrated through',
    'severity': 'Severity',
    'urgencylevel': 'Urgency level',
    'activeperiod': 'Active period',
    'temporalscope': 'Temporal scope',
    'affectedparties': 'Affected parties',
    'obligatedparty': 'Obligated party',
    'constrainedentity': 'Constrained entity',
    'possessedby': 'Possessed by',
    'usedby': 'Used by',
    'usedincontext': 'Used in context',
    'appliedto': 'Applied to',
    'triggeringevent': 'Triggering event',
    'invokedby': 'Invoked by',
    'terminatedby': 'Terminated by',
    'focus': 'Focus',
    'subject': 'Subject',
    # Conclusion / question / decision fields
    'conclusiontext': 'Conclusion',
    'conclusiontype': 'Conclusion type',
    'conclusionnumber': 'Conclusion number',
    'questiontext': 'Question',
    'questiontype': 'Question type',
    'questionnumber': 'Question number',
    'decisionquestion': 'Decision question',
    'decisionpointid': 'Decision point',
    'extractionreasoning': 'Reasoning',
    # Repeated-singular analysis predicates (replaced the numbered
    # option1/citedProvision1/... families, 2026-07-04)
    'option': 'Option',
    'citedprovision': 'Cited provision',
    'answersquestion': 'Answers question',
    'causalstep': 'Causal step',
    # Evidence / provenance (used by the detail page groups)
    'sourcetext': 'Source text',
    'textreferences': 'Text references',
    'documenttitle': 'Document title',
    'discoveredincase': 'Discovered in case',
    'discoveredinpass': 'Discovered in pass',
    'discoveredinsection': 'Discovered in section',
    'firstdiscoveredat': 'First discovered',
    'firstdiscoveredincase': 'First case',
    'generatedattime': 'Generated',
    'wasattributedto': 'Attributed to',
    'wasgeneratedby': 'Generated by',
    'createdby': 'Created by',
    'conceptcategory': 'Concept category',
    'importance': 'Importance',
    'confidence': 'Confidence',
}


# Namespace prefixes for the object properties that appear on individuals, used
# only to show the qualified predicate form in a tooltip. Unknown predicates
# fall back to the bare name (see qualify_predicate).
PREDICATE_NAMESPACES = {
    'hasobligation': 'proeth-core',
    'adherestoprinciple': 'proeth-core',
    'competeswith': 'proeth-core',
    'prevailsover': 'proeth-core',
    'defeasibleunder': 'proeth-core',
    # Promoted to core in v2.8.0 (the deprecated intermediate twin was deleted
    # 2026-07-04); the committed edges are proeth-core:derivedFromPrinciple.
    'derivedfromprinciple': 'proeth-core',
    'citesprovision': 'proeth-core',
    'obligatedparty': 'proeth-core',
}


def qualify_predicate(key):
    """Return the namespace-qualified predicate (e.g. 'proeth-core:hasObligation')
    for a known object property, or the bare key if the namespace is unknown.
    Used for the relationship tooltip on the cards."""
    if not key:
        return key
    prefix = PREDICATE_NAMESPACES.get(key.lower())
    return f"{prefix}:{key}" if prefix else key


def humanize_key(key):
    """Return a human-readable label for a property key.

    Uses the curated map first (case-insensitive), then falls back to splitting
    snake_case and camelCase and title-casing the result.
    """
    if not key:
        return key
    mapped = PROPERTY_LABELS.get(key.lower())
    if mapped:
        return mapped
    spaced = key.replace('_', ' ')
    spaced = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', spaced)
    spaced = re.sub(r'(?<=[A-Z])(?=[A-Z][a-z])', ' ', spaced)
    return spaced[0].upper() + spaced[1:] if spaced else key
